site_name: bsp_tool docs
site_url: https://snake-biscuits.github.io/bsp_tool_docs
repo_url: https://github.com/snake-biscuits/bsp_tool

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.top
    - navigation.tracking
  icon:
    logo: material/tools
    # TODO: favicon
    repo: fontawesome/brands/github

plugins:
  - search
  - link-embeds

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  # NOTE: mermaid is available, but still unwieldy
  # -- could use "erDiagram" for lump systems though
  #   - pymdownx.superfences:
  #       custom_fences:
  #         - name: mermaid
  #           class: mermaid
  #           format: !!python/name:pymdownx.superfences.fence_code_format

