site_name: bsp_tool docs
site_url: https://snake-biscuits.github.io/bsp_tool_docs
repo_url: https://github.com/snake-biscuits/bsp_tool

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.top
    - navigation.tracking
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - link-embeds

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

