name: Build Static HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install latest bsp_tool
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/snake-biscuits/bsp_tool.git
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # TODO: npm / node.js / typescript

    # TODO: build docs from bsp_tool
